version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - exhaustruct
    - ginkgolinter
    - godot
    - godox
    - goheader
    - gosmopolitan
    - ireturn
    - lll
    - misspell
    - nakedret
    - noinlineerr
    - nonamedreturns
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tparallel
    - unparam
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 20
      package-average: 10
    dupl:
      threshold: 250
    errcheck:
      check-type-assertions: true
      check-blank: true
    errchkjson:
      report-no-exported: true
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
        - pattern: http\.Default(Client|Transport)
    funlen:
      lines: 100
      statements: 40
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 20
    godot:
      exclude:
        - '^fixme:'
        - '^todo:'
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: we only want to use the google uuid lib for consistency
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: we only want to use the google uuid lib for consistency
          - github.com/twinj/uuid:
              recommendations:
                - github.com/google/uuid
              reason: we only want to use the google uuid lib for consistency
          - github.com/Clarilab/slacklogger:
              recommendations:
                - github.com/Clarilab/slacklogger/v2
              reason: we want to update this dependency
        versions:
          - github.com/savsgio/atreugo/v11:
              version: '>11.9.9'
              reason: introduced breaking changes
    govet:
      disable:
        - shadow
        - fieldalignment
        - loopclosure
      enable-all: true
    grouper:
      import-require-single-import: true
    lll:
      line-length: 160
    mnd:
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets
        - prometheus.ExponentialBucketsRange
        - prometheus.LinearBuckets
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - funlen
        - lll
        - wrapcheck
    nonamedreturns:
      report-error-in-defer: true
    paralleltest:
      ignore-missing: true
    predeclared:
      qualified-name: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: bare-return
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: early-return
          severity: warning
          disabled: true
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: unused-receiver
          disabled: true
    staticcheck:
      checks:
        - -ST1000
        - -ST1020
        - -ST1021
        - -ST1022
        - all
    tagalign:
      align: false
      order:
        - json
        - bson
        - validate
    varnamelen:
      min-name-length: 2
      ignore-names:
        - i
        - j
        - k
      ignore-decls:
        - c echo.Context
        - t testing.T
        - T any
        - m map[string]int
    wrapcheck:
      ignore-package-globs:
        - github.com/savsgio/atreugo/*
    wsl:
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupword
          - godot
          - lll
          - misspell
          - tagalign
          - whitespace
        source: ^//\s*go:generate\s
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - gochecknoglobals
        source: jsoniter
      - linters:
          - bodyclose
          - containedctx
          - cyclop
          - dupl
          - errcheck
          - forbidigo
          - funlen
          - gochecknoglobals
          - goconst
          - gocyclo
          - gosec
          - mnd
          - nlreturn
          - noctx
          - varnamelen
          - wrapcheck
        path: _test\.go
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - cmd
      - config
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
severity:
  default: warning
  rules:
    - linters:
        - asciicheck
        - bidichk
        - containedctx
        - durationcheck
        - err113
        - errchkjson
        - errorlint
        - exportloopref
        - gocheckcompilerdirectives
        - gochecknoinits
        - ineffassign
        - loggercheck
        - makezero
        - unparam
        - unused
      severity: error
    - linters:
        - dupword
        - gci
        - goconst
        - godot
        - gofmt
        - goimports
        - nakedret
      severity: info
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
        - pattern: a[0:b]
          replacement: a[:b]
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - cmd
      - config
      - third_party$
      - builtin$
      - examples$
